### PR TITLE
Add storage options kwargs to FPGen

### PR DESCRIPTION
**Pull request by mg515**
# Description

`FilePathGenerator` does not expose storage options, used by `fsspec` when instantiating a filesystem. This can prove to be problematic, when advanced options are needed for accessing the data, e.g. when needing `requester_pays` argument for accessing data within google bucket. This change adds such `kwargs` to the constructor of `FilePathGenerator` object, which are passed onto `fsspec`.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [x] Lint and unit tests pass locally with my changes
- [x] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] All dependency changes have been reflected in the pip requirement files.

### CODE REVIEW

**Comment by mg515** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by AlirezaSohofi — DISMISSED** [review]
LG :+1: 
please don't forget to bump the patch version

**Review by AlpAribal — APPROVED** [review]
LGTM, thanks!

**Comment by AlirezaSohofi** [comment]
@mg515 It should be possible to pass these kwargs from high-level api too, i.e. `driver.get_iter()`. [keys_kwargs](https://github.com/merantix-momentum/squirrel-core/blob/main/squirrel/driver/driver.py#L134) is already accepting this kwargs, and it's passed to FPGen too. It's not very obvious though to the user what is passed where. Feel free to improve this if you like, but not necessary for this pr.

**Pull request merged**
