### PR TITLE
zip multiple iterables as a source

### PR DESCRIPTION
**Pull request by AlirezaSohofi**
# Description

The use case: we have a store with samples, and `1..n` other stores that each contain only features. These stores must have the same keys and same number of samples per shard.  

`IterableZipSource` makes it possible to zip items from several iterables and use that as a source. For instance:

```
it1 = MessagepackDriver(url1).get_iter()
it2 = MessagepackDriver(url2).get_iter()

it3 = IterableZipSource(iterables=[it1, it2]).collect()

```

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/usage/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

### CODE REVIEW

**Review by mg515 — APPROVED** [review]
Thanks, LG!

**Comment by AlirezaSohofi** [comment]
@AlpAribal 

what do you think about `ZipDriver` instead? It would accept an iterable of drivers, which should all have the exact same keys and number of items in each shard, and produces a tuple of samples retrieved from each driver.

**Comment by AlpAribal** [comment]
> what do you think about `ZipDriver` instead? It would accept an iterable of drivers, which should all have the exact same keys and number of items in each shard, and produces a tuple of samples retrieved from each driver.

I am not sure how common of a use case this is, so it requires a separate driver. If we see that separating sample features into different stores is unavoidable/meaningful, and converge to such storage patterns, then a zipping driver would definitely make sense.
Though, I feel it will get harder to maintain the more shallow wrappers we have around zip/itertools/more_itertools.

**Comment by AlirezaSohofi** [comment]
> If we see that separating sample features into different stores is unavoidable/meaningful, and converge to such storage patterns, then a zipping driver would definitely make sense.

totally agree. Additionally, the performance would be worse, but it would be more flexible. 

> I am not sure how common of a use case this is

less figure this out.

**Comment by mg515** [comment]
> I am not sure how common of a use case this is

I think it would be a fairly common case. Imagine a ML pipeline starting with writing raw or transformed data in a store. Later, you compute some features for each of the sample. You need another source for that, unless you write in the existing store (I don't think so).
Even later on you might want to compute predictions for each of the models you developed on the same sample set. You generate more and more elements, relating to the sample. It would be cool if there was a way to reliably zip those together in a streaming fashion to e.g. make an analysis.

**Comment by pzdkn** [comment]
I think this PR is useful. I think a iterstream source can be helpful for mapping functions over multiple iterstreams.  This can be helpful independant of drivers.

**Comment by AlirezaSohofi** [comment]
FYI @MaxSchambach

**Comment by pzdkn** [comment]
Actually the new API looks quite good, thanks @AlirezaSohofi

**Pull request closed without merging**
