### PR TITLE
Add name to dataframe driver

### PR DESCRIPTION
**Pull request by pzdkn**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
List any dependencies that are required for this change.

Fixes # issue

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update
- [ ] Refactoring including code style reformatting 
- [ ] Other (please describe):

# Checklist:

- [ ] I have read the [contributing guideline doc](https://squirrel-core.readthedocs.io/en/latest/developer/code_of_conduct.html) (external contributors only)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have kept the PR small so that it can be easily reviewed  
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] All dependency changes have been reflected in the pip requirement files.

### CODE REVIEW

**Review by MaxSchambach — COMMENTED** [review]
Since `DataFrameDriver` is an abstract base class that cannot be instantiated, I am hesitant to add the `name` attribute. Similarly, the base `Driver` class as well as `IterDriver` etc. do not have a `name` attribute. From a user's perspective, the name attribute might suggest that the driver can directly be used, e.g. in the definition of a `Source` which is not the case. Therefore, I would opt for not adding the attribute.

@pzdkn what is your intuition/reason for adding this? Maybe I misunderstand the purpose.

**Review by AlirezaSohofi — APPROVED** [review]
LG :+1:

**Comment by AlirezaSohofi** [comment]
> Since `DataFrameDriver` is an abstract base class that cannot be instantiated, I am hesitant to add the `name` attribute. Similarly, the base `Driver` class as well as `IterDriver` etc. do not have a `name` attribute. From a user's perspective, the name attribute might suggest that the driver can directly be used, e.g. in the definition of a `Source` which is not the case. Therefore, I would opt for not adding the attribute.
> 
> @pzdkn what is your intuition/reason for adding this? Maybe I misunderstand the purpose.

You are right. In terms of functionality it does not matter. If you think it adds confusion rather than clarity we can leave it out.

**Comment by MaxSchambach** [comment]
Yes, since I think it does not add any functionality, as the class cannot be instantiated, and has the potential to create confusion, I would opt for leaving it out.

**Pull request closed without merging**
